# TCL File Generated by Component Editor 23.1
# Tue Mar 11 11:53:59 SGT 2025
# DO NOT MODIFY


# 
# hyperram_controller "Hyper RAM Controller" v0.1
#  2025.03.11.11:53:59
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module hyperram_controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME hyperram_controller
set_module_property VERSION 0.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Hyper RAM Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL hyperram_controller_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file hyperram_controller_top.sv SYSTEM_VERILOG PATH ../ctrl/hyperram_controller_top.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL hyperram_controller_top
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file hyperram_controller_top.sv SYSTEM_VERILOG PATH ../ctrl/hyperram_controller_top.sv


# 
# parameters
# 
add_parameter CSR_ADDR_WIDTH INTEGER 4
set_parameter_property CSR_ADDR_WIDTH DEFAULT_VALUE 4
set_parameter_property CSR_ADDR_WIDTH DISPLAY_NAME CSR_ADDR_WIDTH
set_parameter_property CSR_ADDR_WIDTH TYPE INTEGER
set_parameter_property CSR_ADDR_WIDTH UNITS None
set_parameter_property CSR_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CSR_ADDR_WIDTH HDL_PARAMETER true
add_parameter CSR_DATA_WIDTH INTEGER 32
set_parameter_property CSR_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property CSR_DATA_WIDTH DISPLAY_NAME CSR_DATA_WIDTH
set_parameter_property CSR_DATA_WIDTH TYPE INTEGER
set_parameter_property CSR_DATA_WIDTH UNITS None
set_parameter_property CSR_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CSR_DATA_WIDTH HDL_PARAMETER true
add_parameter MEM_ADDR_WIDTH INTEGER 24
set_parameter_property MEM_ADDR_WIDTH DEFAULT_VALUE 24
set_parameter_property MEM_ADDR_WIDTH DISPLAY_NAME MEM_ADDR_WIDTH
set_parameter_property MEM_ADDR_WIDTH TYPE INTEGER
set_parameter_property MEM_ADDR_WIDTH UNITS None
set_parameter_property MEM_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MEM_ADDR_WIDTH HDL_PARAMETER true
add_parameter MEM_DATA_WIDTH INTEGER 32
set_parameter_property MEM_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property MEM_DATA_WIDTH DISPLAY_NAME MEM_DATA_WIDTH
set_parameter_property MEM_DATA_WIDTH TYPE INTEGER
set_parameter_property MEM_DATA_WIDTH UNITS None
set_parameter_property MEM_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MEM_DATA_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 100000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point mem
# 
add_interface mem avalon end
set_interface_property mem addressUnits WORDS
set_interface_property mem associatedClock clock
set_interface_property mem associatedReset reset
set_interface_property mem bitsPerSymbol 8
set_interface_property mem burstOnBurstBoundariesOnly false
set_interface_property mem burstcountUnits WORDS
set_interface_property mem explicitAddressSpan 0
set_interface_property mem holdTime 0
set_interface_property mem isNonVolatileStorage true
set_interface_property mem linewrapBursts false
set_interface_property mem maximumPendingReadTransactions 8
set_interface_property mem maximumPendingWriteTransactions 0
set_interface_property mem readLatency 0
set_interface_property mem readWaitTime 1
set_interface_property mem setupTime 0
set_interface_property mem timingUnits Cycles
set_interface_property mem writeWaitTime 0
set_interface_property mem ENABLED true
set_interface_property mem EXPORT_OF ""
set_interface_property mem PORT_NAME_MAP ""
set_interface_property mem CMSIS_SVD_VARIABLES ""
set_interface_property mem SVD_ADDRESS_GROUP ""

add_interface_port mem avs_mem_address address Input "((MEM_ADDR_WIDTH-1)) - (0) + 1"
add_interface_port mem avs_mem_read read Input 1
add_interface_port mem avs_mem_readdata readdata Output "((MEM_DATA_WIDTH-1)) - (0) + 1"
add_interface_port mem avs_mem_write write Input 1
add_interface_port mem avs_mem_writedata writedata Input "((MEM_DATA_WIDTH-1)) - (0) + 1"
add_interface_port mem avs_mem_waitrequest waitrequest Output 1
add_interface_port mem avs_mem_readdatavalid readdatavalid Output 1
set_interface_assignment mem embeddedsw.configuration.isFlash 0
set_interface_assignment mem embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment mem embeddedsw.configuration.isNonVolatileStorage 1
set_interface_assignment mem embeddedsw.configuration.isPrintableDevice 0


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock
set_interface_property csr associatedReset reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr maximumPendingWriteTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr avs_csr_address address Input "((CSR_ADDR_WIDTH-1)) - (0) + 1"
add_interface_port csr avs_csr_read read Input 1
add_interface_port csr avs_csr_readdata readdata Output "((CSR_DATA_WIDTH-1)) - (0) + 1"
add_interface_port csr avs_csr_write write Input 1
add_interface_port csr avs_csr_writedata writedata Input "((CSR_DATA_WIDTH-1)) - (0) + 1"
add_interface_port csr avs_csr_waitrequest waitrequest Output 1
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0

